import { DEFAULT_EMOJIS } from "./emoji.js";
export const EMOJI_CATEGORIES = [{ label: "🌈 ایموجی‌های سراسری", items: [
  { key: "check", label: "تیک" },
  { key: "cross", label: "ضربدر" },
  { key: "warning", label: "هشدار" },
  { key: "success", label: "موفقیت" },
  { key: "info", label: "اطلاعات" },
  { key: "back", label: "بازگشت" },
  { key: "home", label: "خانه" },
  { key: "user", label: "کاربر" },
  { key: "users", label: "کاربران" },
  { key: "admin", label: "ادمین" },
  { key: "support", label: "پشتیبانی" },
  { key: "ai", label: "هوش مصنوعی" },
  { key: "wallet", label: "کیف پول" },
  { key: "card", label: "کارت" },
  { key: "receipt", label: "رسید" },
  { key: "service", label: "سرویس" },
  { key: "buy", label: "خرید" },
  { key: "test", label: "تست" },
  { key: "settings", label: "تنظیمات" },
  { key: "backup", label: "بکاپ" },
  { key: "broadcast", label: "پیام همگانی" },
  { key: "stats", label: "آمار" },
  { key: "time", label: "زمان" },
  { key: "warning2", label: "هشدار جدی" },
  { key: "link", label: "لینک" },
  { key: "lock", label: "قفل" },
  { key: "unlock", label: "باز کردن" },
  { key: "trash", label: "حذف" },
  { key: "search", label: "جستجو" },
  { key: "gift", label: "هدیه" },
  { key: "rocket", label: "موشک" },
  { key: "robot", label: "ربات" },
  { key: "fire", label: "آتش" },
  { key: "phone", label: "تلفن" },
  { key: "calendar", label: "تقویم" },
] }];
