// 3x-ui / Sanaei adapter
async function login(panel){const r=await fetch(`${panel.url}/login`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({username:panel.username,password:panel.password}),redirect:"manual"});const c=r.headers.get("set-cookie");if(!c)throw Error("3x-ui login failed");return c.split(";")[0];}
async function getInbound(panel,cookie,id){const r=await fetch(`${panel.url}/panel/api/inbounds/get/${encodeURIComponent(id)}`,{headers:{Cookie:cookie}});if(!r.ok)throw Error(`3x-ui inbound ${r.status}`);const d=await r.json();if(!d.obj)throw Error("inbound not found");return d.obj;}
async function updateClient(panel,profile,username,fn){const c=await login(panel),ib=await getInbound(panel,c,profile.inbound_id);const st=typeof ib.settings==="string"?JSON.parse(ib.settings||"{}"):ib.settings||{};const cs=st.clients||[];const i=cs.findIndex(x=>x.email===username||x.id===username);if(i<0)throw Error("3x-ui client not found");const client={...cs[i]};fn(client);const r=await fetch(`${panel.url}/panel/api/inbounds/updateClient/${encodeURIComponent(client.id)}`,{method:"POST",headers:{Cookie:c,"Content-Type":"application/json"},body:JSON.stringify({id:profile.inbound_id,settings:JSON.stringify({clients:[client]})})});if(!r.ok)throw Error(`3x-ui update ${r.status}: ${await r.text()}`);return client;}
export async function testConnection(panel){try{await login(panel);return{ok:true}}catch(e){return{ok:false,error:String(e)}}}
export async function createUser(panel,profile,{username,volumeGB,days}){const c=await login(panel),id=crypto.randomUUID(),subId=crypto.randomUUID().replace(/-/g,"").slice(0,16);const client={id,subId,email:username,enable:true,expiryTime:Date.now()+days*86400000,totalGB:volumeGB>0?volumeGB*1073741824:0};const r=await fetch(`${panel.url}/panel/api/inbounds/addClient`,{method:"POST",headers:{Cookie:c,"Content-Type":"application/json"},body:JSON.stringify({id:profile.inbound_id,settings:JSON.stringify({clients:[client]})})});if(!r.ok)throw Error(`3x-ui add ${r.status}: ${await r.text()}`);return{username,client_id:id,sub_id:subId,inbound_id:profile.inbound_id,subscription_url:`${panel.subscription_base_url||panel.url}/sub/${subId}`,raw:client};}
export async function getUser(panel,inboundId,emailMaybe){const email=typeof emailMaybe==="undefined"?inboundId:emailMaybe;const c=await login(panel);const r=await fetch(`${panel.url}/panel/api/inbounds/getClientTraffics/${encodeURIComponent(email)}`,{headers:{Cookie:c}});if(!r.ok)return null;const d=await r.json(),t=d.obj;if(!t)return null;return{username:email,used_traffic_bytes:(t.up||0)+(t.down||0),data_limit_bytes:t.total||0,expire:t.expiryTime?Math.floor(t.expiryTime/1000):null,status:t.enable===false?"disabled":"active",sub_id:t.subId||null};}
export async function disableUser(panel,profile,username){await updateClient(panel,profile,username,c=>{c.enable=false;});}
export async function renewUser(panel,profile,username,{volumeGB,days}){await updateClient(panel,profile,username,c=>{c.enable=true;c.expiryTime=Date.now()+Number(days)*86400000;if(volumeGB!==undefined)c.totalGB=Number(volumeGB)*1073741824;});}
export async function addVolume(panel,profile,username,extraGB,currentTotalGB){await updateClient(panel,profile,username,c=>{c.enable=true;c.totalGB=Math.max(Number(c.totalGB||0),Number(currentTotalGB||0)*1073741824)+Number(extraGB)*1073741824;});}
export async function extendUser(panel,profile,username,extraDays,currentExpiry){await updateClient(panel,profile,username,c=>{c.enable=true;c.expiryTime=Math.max(Number(c.expiryTime||0),Number(currentExpiry||Date.now()))+Number(extraDays)*86400000;});}
export async function deleteUser(panel,profile,username){await disableUser(panel,profile,username);}
export async function regenerateSubscription(panel,profile,username){const c=await updateClient(panel,profile,username,x=>{x.subId=crypto.randomUUID().replace(/-/g,"").slice(0,16)});return `${panel.subscription_base_url||panel.url}/sub/${c.subId}`;}
