name = "vpn-shop-bot"
main = "src/index.js"
compatibility_date = "2024-09-01"

================================

KV Namespaces

================================

kv_namespaces = [
{ binding = "BOT_KV", id = "2dc3b08851bf4d86b542cb1334b8381d" },
{ binding = "BOT_SESSIONS", id = "c52b2e299bf194abfb106edcddeb3aa55" }
]

================================

Environment Variables

================================

[vars]
BOT_NAME = "Vj"
BOT_USERNAME = "Vj_PANEL_BOT"

================================

Cron Jobs

================================

[triggers]
crons = ["*/15 * * * *"]

================================

Durable Objects

================================

[[durable_objects.bindings]]
name = "WALLET_LOCK"
class_name = "WalletLock"

SQLite-backed Durable Object migration

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WalletLock"]
